title:             kun의 기술 블로그
email:             gsr2732@example.com
description:       일상적 개발 이야기
author:            g1stkun
baseurl:           "/"
url:               "http://g1stkun.github.io"

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
